# Generated by Django 4.1.2 on 2022-10-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0003_registration_usertype_alter_registration_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[('1', 'Mental Health'), ('2', 'Health Disease'), ('3', 'covid-19'), ('4', 'Immunization')], max_length=20, null=True),
        ),
    ]
