# Generated by Django 4.1.2 on 2022-11-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0004_alter_topic_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificationmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('issuer_name', models.CharField(max_length=50)),
                ('reciever_name', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=1000)),
            ],
        ),
    ]
